// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLClvP_AoT5gvdtTX42Y7dsu8SKBIkmVQ',
    appId: '1:465139698048:web:2179ed5ad748a422785965',
    messagingSenderId: '465139698048',
    projectId: 'product-finder-c9db4',
    authDomain: 'product-finder-c9db4.firebaseapp.com',
    storageBucket: 'product-finder-c9db4.firebasestorage.app',
    measurementId: 'G-Q2N1RH3VDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbybx2dc4SgJj2WbKujgU3tUKTZSi48Dc',
    appId: '1:465139698048:android:a9fda12980e0b750785965',
    messagingSenderId: '465139698048',
    projectId: 'product-finder-c9db4',
    storageBucket: 'product-finder-c9db4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuImnBW2ZdKCortslyJ5sWNYyJOEj32MA',
    appId: '1:465139698048:ios:ed43ea3cfebda29c785965',
    messagingSenderId: '465139698048',
    projectId: 'product-finder-c9db4',
    storageBucket: 'product-finder-c9db4.firebasestorage.app',
    iosClientId: '465139698048-ld97co1nc4aak3529g0rdsoh9vnlvdqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.productFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuImnBW2ZdKCortslyJ5sWNYyJOEj32MA',
    appId: '1:465139698048:ios:ed43ea3cfebda29c785965',
    messagingSenderId: '465139698048',
    projectId: 'product-finder-c9db4',
    storageBucket: 'product-finder-c9db4.firebasestorage.app',
    iosClientId: '465139698048-ld97co1nc4aak3529g0rdsoh9vnlvdqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.productFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLClvP_AoT5gvdtTX42Y7dsu8SKBIkmVQ',
    appId: '1:465139698048:web:ef2a6e8e5d7d7fff785965',
    messagingSenderId: '465139698048',
    projectId: 'product-finder-c9db4',
    authDomain: 'product-finder-c9db4.firebaseapp.com',
    storageBucket: 'product-finder-c9db4.firebasestorage.app',
    measurementId: 'G-2MBDQT8EJS',
  );
}
